apiVersion: v1
kind: Secret

metadata:
  name: flask-secret
  namespace: flaskapp

type: Opaque

stringData:
  PRODUCTION_DATABASE_URL: postgresql+psycopg2://testuser:testpass@postgres-service:5432/testdb
  #PRODUCTION_DATABASE_URL: postgresql+psycopg2://wrongdb@postgres-service:5432/testdb

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flaskapp
type: Opaque
stringData:
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  POSTGRES_DB: testdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: flaskapp
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432